import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";

const PROJECTS_DIR = path.join(process.cwd(), "content/projects");
const MANIFEST_PATH = path.join(process.cwd(), "lib/generated/thumbs.json");

export type ProjectFrontmatter = {
  title: string;
  year: number;
  tags: string[];
  thumbnail: string;
  order: number;
  summary?: string;
};

/** Serializable shape passed to client components (Works section). */
export type ProjectSummary = ProjectFrontmatter & {
  slug: string;
  /** 512px WebP generated by scripts/thumbnails.mjs, falls back to the original. */
  thumb: string;
  blurDataURL?: string;
  atlasIndex: number;
};

export type Project = ProjectSummary & { content: string };

type ThumbManifest = {
  atlas: { src: string; cols: number; rows: number };
  projects: Record<string, { thumb: string; blurDataURL: string; atlasIndex: number }>;
};

async function readManifest(): Promise<ThumbManifest | null> {
  try {
    return JSON.parse(await fs.readFile(MANIFEST_PATH, "utf8"));
  } catch {
    return null;
  }
}

export async function getAtlas() {
  return (await readManifest())?.atlas ?? null;
}

async function readProject(file: string, manifest: ThumbManifest | null): Promise<Project> {
  const slug = file.replace(/\.mdx$/, "");
  const { data, content } = matter(await fs.readFile(path.join(PROJECTS_DIR, file), "utf8"));
  const fm = data as ProjectFrontmatter;
  const generated = manifest?.projects[slug];
  return {
    slug,
    title: fm.title,
    year: Number(fm.year),
    tags: fm.tags ?? [],
    thumbnail: fm.thumbnail,
    order: Number(fm.order ?? 999),
    summary: fm.summary,
    thumb: generated?.thumb ?? fm.thumbnail,
    blurDataURL: generated?.blurDataURL,
    atlasIndex: generated?.atlasIndex ?? -1,
    content,
  };
}

export async function getAllProjects(): Promise<ProjectSummary[]> {
  const manifest = await readManifest();
  const files = (await fs.readdir(PROJECTS_DIR)).filter((f) => f.endsWith(".mdx"));
  const projects = await Promise.all(files.map((f) => readProject(f, manifest)));
  return projects
    .sort((a, b) => a.order - b.order || b.year - a.year)
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    .map(({ content, ...summary }) => summary);
}

export async function getProjectBySlug(slug: string): Promise<Project | null> {
  if (!/^[a-z0-9-]+$/i.test(slug)) return null;
  try {
    return await readProject(`${slug}.mdx`, await readManifest());
  } catch {
    return null;
  }
}
